### ISSUE TITLE
数据整理

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/tls_atack#1]
智渤 @storyinvisible ，

我在原来的文件夹下上传了一个9k.xlsx文件。这个文件的数据来自于你的9k.csv。你接下来的任务是把这个表格填写好，主要分以下几个方面。

1. summary标签页

在这个excel文档的9k标签页的最后一行，有一个SUM，它统计了每一个attack在ok, low, medium和high的数量。你根据summary页的表格格式，把哪些attack在ok, low, medium和high的数量填写好。注意，还有一列timeout的信息。如果昨天所说，有一些网站timeout了，这个数据我们也应该要有（暂时你就把总数量减去ok, low, medium和high的数量吧，希望空白单元格产生的原因真的只有timeout）。

2. 统计出每一类attack严重程度为high的网站

你在表格里可以看到，secure_client_renego, breach等标签页，在这些标签页中，你填写一下哪些网站是high就好了。

**Comment by storyinvisible** [comment]
Done, For timeout, I believe for breach_cbc_tls1 is not solely because of timeout issue, but not under the scope of this test.

**Comment by llmhyy** [comment]
Hi @storyinvisible  

Then, what are the other reason of blank cells?

**Comment by storyinvisible** [comment]
<img width="799" alt="not tested" src="https://user-images.githubusercontent.com/30903626/49789699-964eb700-fd67-11e8-9d95-d03ae3573a06.PNG">
I doubted these two tests because they do not make statistical sense, thus trial test was conducted. Refer to the images, The test which refers to the Logjam-common primes and beast_CBC_TLS1 were not tested for the URL. Thus , I assume that the most of the blank on these two tests are not conducted for the URL .
The other attacks has number of tests that are very similar to heartbleed, which had conducted on all URL, for this, we can deduce that the rest of the blank on those test are due to timeout.

**Comment by llmhyy** [comment]
Thanks @storyinvisible , let's put this issue aside.
